package level;

import objects.Block;
import objects.House;
import objects.Player;
import objects.Street;
import objects.Character;
import org.newdawn.slick.Graphics;
import org.newdawn.slick.geom.Shape;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Robin on 08.01.2017.
 * This is a dummy level class for dev. All other level classes musst be generated by codegenerator.
 */
public class DummyLevel implements ILevel {

    public static final String LEVEL_NAME = "Dummy Level";

    /*The player for this level*/
    private Player player;
    /*The time player have to survive in this level in s*/
    private float time;

    private List<Block> blocks;

    /**
     * only used for performance since blocks do not change over playtime
     */
    private List<Shape> blockShapes;


    /*creates this level. here all the input of the text file must be used for crating this level*/
    public DummyLevel() {

        /*
         * Level is 800x640 blocks, one block is 32*32 pix... -> Level = 25x20 Blocks
         */

        this.blocks = new ArrayList<Block>();
        time = 0.001f;
        this.player = new Player(16, 16, 16, true, 1f);
//        blocks.add(new Street(16, 16, 32, false));
//        blocks.add(new Street(48, 16, 32, false));
//        blocks.add(new Street(80, 16, 32, false));
//        blocks.add(new Street(112, 16, 32, false));
//        blocks.add(new Street(144, 16, 32, false));
//        blocks.add(new Street(176, 16, 32, false));
//        blocks.add(new Street(208, 16, 32, false));
//        blocks.add(new Street(240, 16, 32, false));
//        blocks.add(new Street(272, 16, 32, false));
//        blocks.add(new Street(304, 16, 32, false));
//        blocks.add(new Street(336, 16, 32, false));
//        blocks.add(new Street(368, 16, 32, false));
//        blocks.add(new Street(400, 16, 32, false));
//        blocks.add(new Street(432, 16, 32, false));
//        blocks.add(new Street(464, 16, 32, false));
//        blocks.add(new Street(496, 16, 32, false));
//        blocks.add(new Street(528, 16, 32, false));
//        blocks.add(new Street(560, 16, 32, false));
//        blocks.add(new Street(592, 16, 32, false));
//        blocks.add(new Street(624, 16, 32, false));
//        blocks.add(new Street(656, 16, 32, false));
//        blocks.add(new Street(688, 16, 32, false));
//        blocks.add(new Street(720, 16, 32, false));
//        blocks.add(new Street(752, 16, 32, false));
//        blocks.add(new Street(784, 16, 32, false));
//        blocks.add(new Street(16, 48, 32, false));
//        blocks.add(new Street(48, 48, 32, false));
//        blocks.add(new Street(80, 48, 32, false));
//        blocks.add(new Street(112, 48, 32, false));
//        blocks.add(new Street(144, 48, 32, false));
//        blocks.add(new Street(176, 48, 32, false));
//        blocks.add(new Street(208, 48, 32, false));
//        blocks.add(new Street(240, 48, 32, false));
//        blocks.add(new Street(272, 48, 32, false));
//        blocks.add(new Street(304, 48, 32, false));
//        blocks.add(new Street(336, 48, 32, false));
//        blocks.add(new Street(368, 48, 32, false));
//        blocks.add(new Street(400, 48, 32, false));
//        blocks.add(new Street(432, 48, 32, false));
//        blocks.add(new Street(464, 48, 32, false));
//        blocks.add(new Street(496, 48, 32, false));
//        blocks.add(new Street(528, 48, 32, false));
//        blocks.add(new Street(560, 48, 32, false));
//        blocks.add(new Street(592, 48, 32, false));
//        blocks.add(new Street(624, 48, 32, false));
//        blocks.add(new Street(656, 48, 32, false));
//        blocks.add(new Street(688, 48, 32, false));
//        blocks.add(new Street(720, 48, 32, false));
//        blocks.add(new Street(752, 48, 32, false));
//        blocks.add(new Street(784, 48, 32, false));
//        blocks.add(new Street(16, 80, 32, false));
//        blocks.add(new Street(48, 80, 32, false));
//        blocks.add(new Street(80, 80, 32, false));
//        blocks.add(new Street(112, 80, 32, false));
//        blocks.add(new Street(144, 80, 32, false));
//        blocks.add(new Street(176, 80, 32, false));
//        blocks.add(new Street(208, 80, 32, false));
//        blocks.add(new Street(240, 80, 32, false));
//        blocks.add(new Street(272, 80, 32, false));
//        blocks.add(new Street(304, 80, 32, false));
//        blocks.add(new Street(336, 80, 32, false));
//        blocks.add(new Street(368, 80, 32, false));
//        blocks.add(new Street(400, 80, 32, false));
//        blocks.add(new Street(432, 80, 32, false));
//        blocks.add(new Street(464, 80, 32, false));
//        blocks.add(new Street(496, 80, 32, false));
//        blocks.add(new Street(528, 80, 32, false));
//        blocks.add(new Street(560, 80, 32, false));
//        blocks.add(new Street(592, 80, 32, false));
//        blocks.add(new Street(624, 80, 32, false));
//        blocks.add(new Street(656, 80, 32, false));
//        blocks.add(new Street(688, 80, 32, false));
//        blocks.add(new Street(720, 80, 32, false));
//        blocks.add(new Street(752, 80, 32, false));
//        blocks.add(new Street(784, 80, 32, false));
//
//        blocks.add(new Street(16, 112, 32, false));
//        blocks.add(new Street(48, 112, 32, false));
//        blocks.add(new Street(80, 112, 32, false));
//        blocks.add(new Street(112, 112, 32, false));
//        blocks.add(new Street(144, 112, 32, false));
//        blocks.add(new Street(176, 112, 32, false));
//        blocks.add(new Street(208, 112, 32, false));
//        blocks.add(new Street(240, 112, 32, false));
//        blocks.add(new Street(272, 112, 32, false));
//        blocks.add(new Street(304, 112, 32, false));
//        blocks.add(new Street(336, 112, 32, false));
//        blocks.add(new Street(368, 112, 32, false));
//        blocks.add(new Street(400, 112, 32, false));
//        blocks.add(new Street(432, 112, 32, false));
//        blocks.add(new Street(464, 112, 32, false));
//        blocks.add(new Street(496, 112, 32, false));
//        blocks.add(new Street(528, 112, 32, false));
//        blocks.add(new Street(560, 112, 32, false));
//        blocks.add(new Street(592, 112, 32, false));
//        blocks.add(new Street(624, 112, 32, false));
//        blocks.add(new Street(656, 112, 32, false));
//        blocks.add(new Street(688, 112, 32, false));
//        blocks.add(new Street(720, 112, 32, false));
//        blocks.add(new Street(752, 112, 32, false));
//        blocks.add(new Street(784, 112, 32, false));

        blocks.add(new Street(16, 144, 32, false));
        blocks.add(new House(48, 144, 32, false));
        blocks.add(new Street(80, 144, 32, false));
        blocks.add(new Street(112, 144, 32, false));
        blocks.add(new Street(144, 144, 32, false));
        blocks.add(new House(176, 144, 32, false));
        blocks.add(new House(208, 144, 32, false));
        blocks.add(new House(240, 144, 32, false));
        blocks.add(new Street(272, 144, 32, false));
        blocks.add(new Street(304, 144, 32, false));
        blocks.add(new Street(336, 144, 32, false));
//        blocks.add(new Street(368, 144, 32, false));
//        blocks.add(new Street(400, 144, 32, false));
//        blocks.add(new Street(432, 144, 32, false));
//        blocks.add(new Street(464, 144, 32, false));
//        blocks.add(new Street(496, 144, 32, false));
//        blocks.add(new Street(528, 144, 32, false));
//        blocks.add(new Street(560, 144, 32, false));
//        blocks.add(new Street(592, 144, 32, false));
//        blocks.add(new Street(624, 144, 32, false));
//        blocks.add(new Street(656, 144, 32, false));
//        blocks.add(new Street(688, 144, 32, false));
//        blocks.add(new Street(720, 144, 32, false));
//        blocks.add(new Street(752, 144, 32, false));
//        blocks.add(new Street(784, 144, 32, false));
//
//        blocks.add(new Street(16, 144, 32, false));
//        blocks.add(new Street(48, 144, 32, false));
//        blocks.add(new Street(80, 144, 32, false));
//        blocks.add(new Street(112, 144, 32, false));
//        blocks.add(new Street(144, 144, 32, false));
//        blocks.add(new Street(176, 144, 32, false));
//        blocks.add(new Street(208, 144, 32, false));
//        blocks.add(new Street(240, 144, 32, false));
//        blocks.add(new Street(272, 144, 32, false));
//        blocks.add(new Street(304, 144, 32, false));
//        blocks.add(new Street(336, 144, 32, false));
//        blocks.add(new Street(368, 144, 32, false));
//        blocks.add(new Street(400, 144, 32, false));
//        blocks.add(new Street(432, 144, 32, false));
//        blocks.add(new Street(464, 144, 32, false));
//        blocks.add(new Street(496, 144, 32, false));
//        blocks.add(new Street(528, 144, 32, false));
//        blocks.add(new Street(560, 144, 32, false));
//        blocks.add(new Street(592, 144, 32, false));
//        blocks.add(new Street(624, 144, 32, false));
//        blocks.add(new Street(656, 144, 32, false));
//        blocks.add(new Street(688, 144, 32, false));
//        blocks.add(new Street(720, 144, 32, false));
//        blocks.add(new Street(752, 144, 32, false));
//        blocks.add(new Street(784, 144, 32, false));


    }


    public Player getPlayer() {
        return player;
    }

    /**
     * Returns true if a Character can walk onto the given x and y coordinates
     *
     * @param c
     * @param x
     * @param y
     * @return
     */
    public boolean canIWalkHere(Character c, int x, int y) {
        for (Block block : blocks) {
            if ( block.isBlocking()) {  //TODO make list of all blocking blocks for faster checking
                if(block.checkIfHitBy(c.getHitbox())) {
                    return true;
                }
            }
        }
        return true;
    }

    public float getTime() {
        return time;
    }

    /**
     * Draws all blocks of this map onto a given graphic context
     *
     * @param g Graphics context
     */
    public void drawOnGraphicContext(Graphics g) {
        for (Block block : blocks) {
            g.drawImage(block.getImage(), block.getPos_x(), block.getPos_y());
        }
        g.drawImage(player.getImage(), player.getPos_x(), player.getPos_y());
    }
}
